config/routes.rb
Rails.application.routes.draw do
  resources :pages
  # , except: [:show]
  # get '/pages/:permalink' => "pages#permalink", as: 'permalink'
  get '/search', to: "countries#search"
  # get 'countries/index'
  # get 'countries/show'
  # get 'players/index'
  # get 'players/show'
  resources :countries, only: [:index, :show]
  resources :players, only: [:index, :show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "players#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :players

  validates :name, presence: true
  validates :name, uniqueness: true

  # geocoded_by :address;
  # after_validation :geocode,

  # def address
  #   [name].compact.join(",")
  # end
  # # if: :address_changed?
  # # def address_changed
  # #   name_changed?
  # # end
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :country

  validates :name, :position, :overall, presence: true
  validates :name, uniqueness: true
  validates :overall, numericality: {only_integer: true}

  def self.search(keyword, search_category)
    if keyword.present?
      if keyword && search_category == "All"
        where('name LIKE ?', "%#{keyword}%")
      elsif keyword == " " && search_category != "All"
        joins(:countries).where('countries.id = ?', "%#{search_category}%")
      else
        where('name LIKE ? AND country_id = ?', "%#{keyword}%", "%#{search_category}%")
      end
    else
      all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :cms_pages
  def cms_pages
    Page.all
  end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  def index
    # @q = Country.ransack(params[:q])
    @countries = Country.all.paginate(page: params[:page], per_page: 10)
  end

  def show
    # if params[:location].present?
    #   @country = Country.near(params[:name])
    # else
    #   @country = Country.find(params[:id])
    # end
    # @country = @country.to_gmaps4rails
    @country = Country.find(params[:id])
  end

  def search
    @query = params[:query]
    @countries = Country.paginate(page: params[:page], per_page: 10).where("countries.name LIKE ?",["%#{@query}%"])
    render "index"
    # if @query.empty?
    #   flash[:notice] = "No results found for #{params[:query]}"
    # end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: %i[ show edit update destroy ]
  http_basic_authenticate_with name: "footballers", password: "footballers", except: [:show]

  # GET /pages or /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1 or /pages/1.json
  def show
    @pages = Page.find(params[:id])
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages or /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to page_url(@page), notice: "Page was successfully created." }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1 or /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to page_url(@page), notice: "Page was successfully updated." }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1 or /pages/1.json
  def destroy
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url, notice: "Page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def page_params
      params.require(:page).permit(:title, :content, :permalink)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players =  Player.includes(:country).paginate(page: params[:page], per_page: 10).search(params[:keyword], params[:search_category])
  end

  def show
    @player = Player.find(params[:id])
  end

  # def new
  #   @player = Player.new
  # end

  # def edit

  # end

  # def create
  #   @player = Player.new(task_params)

  #   respond_to do |format|
  #     if @player.save
  #       format.html {redirect_to @player, notice: "Player was added successfully!"}
  #       format.csv { send_data @players.to_csv, filename: "players.csv"}
  #     else
  #       format.html { remder :new}
  #       format.csv { remder csv: @task.errors}
  #     end
  #   end
  # end

  # def update
  #   respond_to do |task_params|
  #     if @player.save
  #       format.html {redirect_to @player, notice: "Player was updated successfully!"}
  #       format.csv { send_data @players.to_csv, filename: "players.csv"}
  #     else
  #       format.html { remder :edit}
  #       format.csv { remder csv: @task.errors}
  #     end
  #   end
  # end

  # def destroy
  #   @player.destroy
  #   respond_to |format|
  #   format.html {redirect_to player_path, notice: "Player was updated successfully!"}
  #   format.csv { head :no content}
  # end

  # private
  #   def set_task

  #   end
  #   def task_params

  #   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/common/_footer.html.erb
<!-- Footer -->
<footer class="bg-dark font-small text-white">
  <!-- Footer Links -->
  <div class="container">
    <!-- Grid row-->
    <div class="row text-center d-flex justify-content-center pt-3 mb-1">
      <!-- Grid column -->
      <div class="col-md-2 mb-3">
        <%= link_to "Players", players_path, class: "nav-link link-light text-uppercase font-weight-bold" %>
      </div>
      <!-- Grid column -->
      <div class="col-md-2 mb-3">
        <%= link_to "Country", countries_path, class: "nav-link link-light text-uppercase font-weight-bold" %>
      </div>
      <!-- Grid column -->
      <!-- Grid column -->
      <div class="col-md-2 mb-3">
        <div class= "nav-link link-light text-uppercase font-weight-bold">
          Club
        </div>
      </div>
      <!-- Grid column -->
      <% cms_pages.each do |page| %>
        <!-- Grid column -->
        <div class="col-md-3 mb-0">
          <%= link_to page.title, pages_path, class: "nav-link link-light text-uppercase font-weight-bold" %>
        </div>
        <!-- Grid column -->
      <% end %>
    </div>
    <!-- Grid row-->
    <hr class="rgba-white-light" style="margin: 0;">
  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-2">
    Copyright<span>&copy;</span>2022 Virk Inc. - All rights reserved
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/common/_header.html.erb
<!-- Navigation Bar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Footballers</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Players", players_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Country", countries_path, class: "nav-link"  %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Club</a>
        </li>
        <% cms_pages.each do |page| %>
          <li class="nav-item">
            <%= link_to page.title, pages_path, class: "nav-link"  %>
          </li>
        <% end %>
      </ul>
      <div class="search-box col-md-5">
      <%= form_tag players_path, method: 'get', id: 'players_search' do %>
      <div class="d-flex">
        <%= text_field_tag :keyword, params[:keyword], class: "form-control" %>
        <%= select_tag :search_category, options_from_collection_for_select(Player.all, "id", "country_id"), :include_blank => 'All', class: "form dropdown-toggle" %>
        <div class="input-group-append">
          <%= submit_tag "Search", name: nil, class: "btn btn-success" %>
        </div>
      </div>
      <% end %>
      </div>
    </div>
  </div>
</nav>
<!-- Navigation Bar-->

app/views/countries/index.html.erb
<section class="content-info">
  <div class="container paddings-mini">
    <div class="row">
      <div class="col-lg-12">
        <h1>Countries</h1>
        <div>
          <!-- Search Form -->
          <form class="input-group" method="GET" action="/search">
            <div class="form-outline">
              <input type="search" placeholder="Search" aria-label="Search" name="query" class="form-control" >
            </div>
            <button type="submit" class="btn btn-primary">
              <i>Search</i>
            </button>
          </form>
          <!-- Search Form -->
          <!-- Pagination -->
            <div aria-label="Page navigation example">
              <ul class="pagination justify-content-end">
                <li class="page-item">
                  <%= will_paginate @players, previous_label: "PREV", next_label: "NEXT", inner_window: 1, outer_window: 0, class: "page-link" %>
                </li>
              </ul>
            </div>
          <!-- Pagination -->
        </div>
        <!-- Table -->
        <% if @countries.empty? %>
          <p>No result found for the <%= params[:query] %></p>
        <% else %>
          <table class="table table-striped table-responsive table-bordered table-hover result-point">
            <thead class="table-dark text-center">
              <tr>
                <th>Id.</th>
                <th>Country</th>
              </tr>
            </thead>
            <tbody class="text-center">
                <% @countries.each do |country| %>
                  <tr>
                    <td><%= country.id %></td>
                    <td><%= link_to country.name, country_path(country) %></td>
                  </tr>
                <% end %>
            </tbody>
          </table>
        <% end %>
        <!-- Table -->
        <!-- Pagination -->
          <div aria-label="Page navigation example">
            <ul class="pagination justify-content-end">
              <li class="page-item">
                <%= will_paginate @players, previous_label: "PREV", next_label: "NEXT", inner_window: 1, outer_window: 0, class: "page-link" %>
              </li>
            </ul>
          </div>
        <!-- Pagination -->
      </div>
    </div>
  </div>
</section>

app/views/countries/show.html.erb
<!-- Player Card -->
<div class="card text-white text-center" style="margin: 50px 500px;" >
  <div class="card-header bg-dark">
    <h1><%= @country.name %></h1>
  </div>
</div>
<!-- Player Card -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Footballers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <%= render partial: 'common/header' %>
  <body>
    <%= yield %>
  </body>
  <%= render partial: 'common/footer' %>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page) do |form| %>
  <% if page.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :permalink, style: "display: block" %>
    <%= form.text_field :permalink %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/_page.html.erb
<div id="<%= dom_id page %>">
  <!-- Member Card -->
  <div class="card text-white text-center" style="margin: 50px 500px;" >
    <div class="card-header bg-dark">
      <%= page.title %>
    </div>
    <div class="card-body bg-secondary">
      <%# <p class="card-text">
        <strong>Title:</strong>
        <%= page.title %>
      <%# </p> %>
      <p class="card-text">
        <%# <strong>Content:</strong> %>
        <%= page.content %>
      </p>

      <p class="card-text">
        <strong>Permalink:</strong>
        <%= page.permalink %>
      </p>
      <div class="card-footer">
        <%= page.title %> Card
      </div>
  </div>
    <!-- Member Card -->
</div>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Show this page", @page %> |
  <%= link_to "Back to pages", pages_path %>
</div>

app/views/pages/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="border border-light p-3 mb-4">
  <h1>Pages
    <%= link_to "New page", new_page_path, class: "btn btn-danger", style: "margin: 0px 0px 0px 30px; width:300px;"%>
  </h1>
</div>

<div id="pages" class="text-center">
  <% @pages.each do |page| %>
    <%= render page %>
      <%= link_to "Show this page", page, class: "btn btn-primary", style: "margin: -70px 0px 0px; width:300px;" %>
  <% end %>
</div>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Back to pages", pages_path %>
</div>

app/views/pages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @page %>

<div>
  <%= link_to "Edit this page", edit_page_path(@page) %> |
  <%= link_to "Back to pages", pages_path %>

  <%= button_to "Destroy this page", @page, method: :delete %>
</div>

app/views/players/index.html.erb
<section class="content-info">
  <div class="container paddings-mini">
    <div class="row">
      <div class="col-lg-12">
      <h1>Players</h1>
      <!-- Pagination -->
        <div aria-label="Page navigation example">
          <ul class="pagination justify-content-end">
            <li class="page-item">
              <%= will_paginate @players, previous_label: "PREV", next_label: "NEXT", inner_window: 1, outer_window: 0, class: "page-link" %>
            </li>
          </ul>
        </div>
        <!-- Pagination -->
        <!--Table -->
        <table class="table table-striped table-responsive table-bordered table-hover result-point">
          <thead class="table-dark text-center">
            <tr>
              <th>Player</th>
              <th>Nationality</th>
              <th>Position</th>
              <th>Overall</th>
            </tr>
          </thead>
          <tbody class="text-center">
            <% @players.each do |player| %>
              <tr>
                <td><%= link_to player.name, player_path(player) %></td>
                <td><%= player.country.name %></td>
                <td><%= player.position %></td>
                <td><%= player.overall %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <!-- Table -->
        <!-- Pagination -->
        <div aria-label="Page navigation example">
          <ul class="pagination justify-content-end">
            <li class="page-item">
              <%= will_paginate @players, previous_label: "PREV", next_label: "NEXT", inner_window: 1, outer_window: 0, class: "page-link" %>
            </li>
          </ul>
        </div>
        <!-- Pagination -->
      </div>
    </div>
  </div>
</section>

app/views/players/show.html.erb
<!-- Player Card -->
<div class="card text-white text-center" style="margin: 50px 500px;" >
  <div class="card-header bg-dark">
    <h1><%= @player.name %></h1>
  </div>
  <div class="card-body bg-secondary">
    <p class="card-text">Nationality: <%= @player.country.name %></p>
    <p class="card-text">Position: <%= @player.position %></p>
    <p class="card-text">Overall: <%= @player.overall %></p>
    <%# <a href="#" class="btn btn-primary">Go somewhere</a> %>
  </div>
  <div class="card-footer text-muted">
    Player Card
  </div>
</div>
<!-- Player Card -->